name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++

    - name: Compile C++ code
      run: g++ -o hello-world main.cpp

    - name: Run the program
      run: ./hello-world
